language: csharp
mono: none
os: windows
group: dev
env:
  - MSBUILD_PATH: "'/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin'"
before_install:
  - export PATH=$MSBUILD_PATH:${PATH}
script:
  - choco install dotnetcore-sdk
  - dotnet --version
  - dotnet build TestGpuProgram.csproj
  - dotnet publish -r win-x64 -c Release TestGpuProgram.csproj
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "bin/**/native/*.exe"
    skip_cleanup: true
    on:
      branch: master
